"""create models

Revision ID: 0f0392e86c16
Revises: 8ab7ae3321c0
Create Date: 2024-03-13 17:02:26.045772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f0392e86c16'
down_revision = '8ab7ae3321c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('access_level', sa.Integer(), nullable=True),
    sa.CheckConstraint('access_level == 1 OR access_level == 2'),
    sa.CheckConstraint('length(name) >= 1'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('length(description) >= 1'),
    sa.CheckConstraint('length(name) >= 1'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_shows_owner_id_users')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.Column('show_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('episode_number >= 1'),
    sa.CheckConstraint('length(description) >= 1'),
    sa.CheckConstraint('length(name) >= 1'),
    sa.CheckConstraint('season_number >= 1'),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], name=op.f('fk_episodes_show_id_shows')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('episode_number', 'season_number', 'show_id', name='unique_showid_epnumsnnumcombo')
    )
    op.create_table('toys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=True),
    sa.Column('toy_number', sa.Integer(), nullable=True),
    sa.CheckConstraint('length(description) >= 1'),
    sa.CheckConstraint('length(name) >= 1'),
    sa.CheckConstraint('price >= 0'),
    sa.CheckConstraint('toy_number >= 1'),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], name=op.f('fk_toys_show_id_shows')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('toy_number', 'show_id', name='unique_showid_toynumcombo')
    )
    op.create_table('user_episodes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], name=op.f('fk_user_episodes_episode_id_episodes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_episodes_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'episode_id')
    )
    op.create_table('user_toys',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('toy_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.CheckConstraint('quantity >= 0'),
    sa.ForeignKeyConstraint(['toy_id'], ['toys.id'], name=op.f('fk_user_toys_toy_id_toys')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_toys_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'toy_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_toys')
    op.drop_table('user_episodes')
    op.drop_table('toys')
    op.drop_table('episodes')
    op.drop_table('shows')
    op.drop_table('users')
    # ### end Alembic commands ###
